#theme: merlot
#remote_theme: pages-themes/architect@v0.2.0
remote_theme: pages-themes/hacker@v0.2.0
title: Adult to child voice conversion
description: Generative models
markdown: kramdown
highlighter: rouge
